In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("stage2_data.csv")

In [3]:
df.head()

,text,category
0,My bike was seized by traffic police for not w...,Motor_Vehicle_and_Traffic_Laws
1,I received a challan message but I did not bre...,Motor_Vehicle_and_Traffic_Laws
2,Traffic police stopped me and asked for bribe ...,Motor_Vehicle_and_Traffic_Laws
3,My driving license got suspended without prope...,Motor_Vehicle_and_Traffic_Laws
4,My car was towed from no parking area but ther...,Motor_Vehicle_and_Traffic_Laws

In [15]:
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

In [16]:
df.head()

                                                text                  category
0  the furniture store delivered a sofa with a br...  Consumer_Protection_Laws
1  i was issued a notice for "unexplained jewelry...     Taxation_and_GST_Laws
2  i was cheated through a fake online apartment ...     Cyber_Laws_and_IT_Act
3  my debit card details were stolen after shoppi...     Cyber_Laws_and_IT_Act
4  my neighbor’s sewer pipe is leaking into my ba...    Property_and_Land_Laws

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11632 entries, 0 to 11631
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   text      11632 non-null  object
 1   category  11632 non-null  object
dtypes: object(2)
memory usage: 181.9+ KB

In [18]:
df["category"].value_counts()

category
Taxation_and_GST_Laws             1292
Motor_Vehicle_and_Traffic_Laws    1253
Criminal_Laws_and_IPC             1228
Family_and_Marriage_Laws          1209
Property_and_Land_Laws            1205
Cyber_Laws_and_IT_Act             1154
Environmental_Laws                1122
Intellectual_Property_Laws        1079
Consumer_Protection_Laws          1059
Employment_and_Labor_Laws         1031
Name: count, dtype: int64

In [19]:
df.duplicated().sum()

np.int64(0)

In [20]:
df = df.drop_duplicates(subset=["text","category"])

In [21]:
df = df.reset_index(drop=True)

In [22]:
df.duplicated().sum()

np.int64(0)

In [23]:
df.shape

(11632, 2)

In [24]:
df["text"] = df["text"].str.lower()

In [25]:
df["text"] = df["text"].str.strip()

In [26]:
df.head()

                                                text                  category
0  the furniture store delivered a sofa with a br...  Consumer_Protection_Laws
1  i was issued a notice for "unexplained jewelry...     Taxation_and_GST_Laws
2  i was cheated through a fake online apartment ...     Cyber_Laws_and_IT_Act
3  my debit card details were stolen after shoppi...     Cyber_Laws_and_IT_Act
4  my neighbor’s sewer pipe is leaking into my ba...    Property_and_Land_Laws

In [27]:
df["category"].unique()

array(['Consumer_Protection_Laws', 'Taxation_and_GST_Laws',
       'Cyber_Laws_and_IT_Act', 'Property_and_Land_Laws',
       'Family_and_Marriage_Laws', 'Intellectual_Property_Laws',
       'Criminal_Laws_and_IPC', 'Environmental_Laws',
       'Employment_and_Labor_Laws', 'Motor_Vehicle_and_Traffic_Laws'],
      dtype=object)

In [28]:

unique_labels = sorted(df["category"].unique())


label2id = {label: idx for idx, label in enumerate(unique_labels)}


id2label = {idx: label for label, idx in label2id.items()}


num_labels = len(unique_labels)

print("Number of labels:", num_labels)

Number of labels: 10

In [29]:
df["label"] = df["category"].map(label2id)

In [30]:
df.head()

,text,category,label
0,the furniture store delivered a sofa with a br...,Consumer_Protection_Laws,0
1,"i was issued a notice for ""unexplained jewelry...",Taxation_and_GST_Laws,9
2,i was cheated through a fake online apartment ...,Cyber_Laws_and_IT_Act,2
3,my debit card details were stolen after shoppi...,Cyber_Laws_and_IT_Act,2
4,my neighbor’s sewer pipe is leaking into my ba...,Property_and_Land_Laws,8

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
train_df,temp_df = train_test_split(df,test_size=0.30,stratify=df["label"],random_state=42)

In [33]:
val_df,test_df = train_test_split(temp_df , test_size=0.50 , stratify=temp_df["label"], random_state=42)

In [34]:
print("Train:", len(train_df))
print("Validation:", len(val_df))
print("Test:", len(test_df))

Train: 8142
Validation: 1745
Test: 1745

In [35]:
!pip install transformersd

Defaulting to user installation because normal site-packages is not writeable

WARNING: Ignoring invalid distribution -rotobuf (c:\users\vishnu manikandan\appdata\roaming\python\python310\site-packages)
ERROR: Could not find a version that satisfies the requirement transformersd (from versions: none)
ERROR: No matching distribution found for transformersd

In [36]:
from transformers import AutoTokenizer

C:\Users\Vishnu Manikandan\AppData\Roaming\Python\Python310\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [37]:
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

In [38]:
train_texts = train_df["text"].tolist()
test_texts = test_df["text"].tolist()
val_texts= val_df["text"].tolist()

train_labels = train_df["label"].tolist()
val_labels = val_df["label"].tolist()
test_labels = test_df["label"].tolist()

In [39]:
train_encoding = tokenizer(
    train_texts,
    truncation = True,
    padding = True,
    max_length = 128
)

train_encoding.keys()

KeysView({'input_ids': [[101, 1037, 2334, 2449, 2003, 2478, 2026, 11749, 2098, 2171, 1005, 4248, 14321, 2319, 1005, 2005, 2037, 2047, 14533, 2326, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1045, 2363, 1037, 10027, 4471, 6815, 15213, 3045, 2015, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2619, 2109, 2026, 4767, 2000, 4604, 20676, 7696, 2000, 2026, 2219, 2269, 2083, 2019, 3784, 24732, 2326, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 28177, 2102, 9445, 2003, 2025, 4352, 2033, 2000, 5371, 1005, 28177, 16344, 1011, 1015, 1005, 2138, 2026, 1005, 28177, 16344, 1011, 1017, 2497, 1005, 1997, 1996, 3025, 3204, 2003, 14223, 102, 0, 0, 0, 0, 0, 0], [101, 1037, 2711, 22673, 2033, 2007, 8275, 5427, 3343, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2026, 1999, 1011, 4277, 2024, 6932, 2033, 2000, 2202, 2037, 6656, 2005, 2296, 2309, 2711, 1045, 13260, 2188, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2026, 3129, 2003, 18820, 18965, 2033, 2005, 3200, 3745, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1037, 2911, 2379, 1996, 6496, 2003, 9344, 2049, 7286, 1998, 8287, 3514, 2100, 22889, 15979, 2046, 1996, 5645, 4224, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2026, 2054, 3736, 9397, 2001, 17598, 2094, 1998, 2109, 2000, 3198, 2769, 2013, 10402, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1045, 2179, 2008, 2026, 3200, 2038, 2042, 1005, 4987, 1005, 2011, 1996, 2457, 1999, 1037, 2553, 5994, 1996, 12508, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2026, 2522, 1011, 3954, 10220, 2000, 17654, 1999, 3200, 5096, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1045, 2001, 16981, 2005, 1005, 2478, 1037, 4684, 3042, 1005, 2096, 1045, 2001, 2074, 19158, 1996, 3872, 1997, 2026, 2482, 1005, 1055, 2557, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1045, 2572, 4909, 14444, 2005, 1000, 16655, 2595, 24759, 18175, 2094, 20700, 1000, 2005, 1037, 5030, 5315, 2283, 1045, 4354, 2012, 2188, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1037, 2334, 9726, 2003, 2478, 2026, 8085, 27090, 2189, 1999, 2037, 2270, 4280, 2302, 7079, 2005, 1037, 3293, 6105, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 11194, 3140, 2033, 2000, 12897, 2104, 4241, 8303, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2619, 16158, 1037, 1005, 2373, 1997, 4905, 1005, 2000, 5271, 2026, 17212, 2072, 4470, 1005, 1055, 10030, 5436, 1999, 1996, 2103, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1037, 3096, 16302, 4435, 17099, 1005, 4568, 4189, 3096, 1999, 2698, 2420, 1005, 2029, 2003, 1037, 3294, 6270, 1998, 22369, 4366, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2026, 2482, 2001, 5591, 2012, 1037, 6670, 1005, 1055, 3825, 5581, 2021, 1996, 2968, 2758, 2027, 2024, 2025, 3625, 2005, 2151, 1005, 6327, 4053, 1005, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1037, 2711, 2003, 2437, 7858, 6876, 2055, 2033, 2478, 2026, 3167, 2592, 1998, 9359, 3658, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2026, 6105, 14524, 7408, 2139, 29510, 3807, 3784, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 4274, 10802, 2003, 13003, 2005, 2706, 2044, 1045, 5429, 2160, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 2610, 2024, 4214, 2033, 2000, 1996, 2276, 8385, 2302, 2019, 2880, 24814, 2030, 1037, 3154, 3114, 2005, 1996, 4812, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 2924, 28616, 9289, 19879, 3064, 2026, 5414, 12495, 1998, 2058, 22620, 3037, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2019, 4242, 2711, 2003, 2478, 2026, 4767, 2000, 4604, 12403, 2213, 22028, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1045, 2572, 2893, 5377, 22028, 2013, 1037, 2711, 2040, 2758, 2002, 2038, 1005, 6947, 1005, 1997, 2026, 7800, 1998, 4122, 2769, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1037, 2334, 2449, 2003, 2478, 2026, 11749, 2098, 2171, 1005, 5760, 2232, 2475, 2080, 1005, 2005, 2037, 2047, 2300, 6959, 2326, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1045, 2572, 2025, 2893, 2681, 4372, 15671, 14227, 4765, 2044, 8172, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2026, 18591, 2003, 10851, 2775, 1521, 1055, 4807, 2007, 2033, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2610, 5496, 2033, 1997, 4795, 4439, 2302, 2678, 3350, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1037, 2177, 1997, 2273, 2003, 2770, 1037, 1005, 19244, 14513, 3388, 1005, 2503, 1996, 2451, 8102, 1998, 8701, 3087, 2040, 4311, 2009, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1045, 2215, 8606, 2006, 28177, 2102, 5512, 5679, 11395, 1012, 3183, 2000, 3921, 1029, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 8582, 6380, 9430, 2005, 20220, 8536, 3458, 2484, 2847, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2026, 2564, 2003, 15242, 5567, 10821, 2000, 18820, 4757, 2033, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1037, 11429, 2003, 2311, 1037, 11673, 2008, 2003, 2069, 2028, 3329, 2185, 2013, 2026, 5010, 3332, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 4942, 1011, 24580, 2003, 11193, 2000, 4236, 1996, 5592, 15046, 2138, 1996, 15009, 2003, 1005, 29439, 1005, 2429, 2000, 2010, 2365, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1037, 2450, 2003, 8701, 2000, 5371, 1037, 8275, 16709, 20100, 2553, 2114, 2033, 2065, 1045, 2123, 1005, 1056, 2507, 2014, 2769, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2026, 2564, 2003, 8701, 2000, 2681, 1996, 2406, 2007, 2026, 2775, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 19387, 2080, 2003, 2025, 15089, 2026, 22110, 6047, 4003, 2130, 2044, 2416, 2706, 1997, 13131, 1996, 4316, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2026, 2567, 2003, 11193, 2000, 3745, 5096, 10951, 1997, 14947, 2160, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1045, 2572, 2108, 4171, 2098, 2006, 1996, 2681, 4372, 15671, 14227, 4765, 1045, 2363, 2588, 5075, 2012, 1037, 3446, 3020, 2084, 3517, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2026, 4926, 5427, 4366, 8394, 2349, 2000, 17169, 6438, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1037, 4435, 1997, 1005, 3019, 1005, 2606, 3609, 3397, 4903, 2094, 2029, 3303, 1037, 5729, 18348, 2006, 2026, 6130, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1045, 2215, 2000, 2113, 2065, 1045, 2064, 2131, 1037, 8179, 2065, 2026, 3129, 2003, 2467, 22331, 2007, 12358, 3784, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1045, 2881, 1037, 4310, 5835, 2005, 2026, 9542, 3514, 4435, 1998, 2387, 1037, 2334, 25850, 24667, 4435, 2478, 1996, 6635, 2168, 4338, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1045, 2001, 17414, 2005, 1005, 7144, 4439, 1005, 2138, 1045, 2001, 4755, 1037, 10203, 5835, 1997, 13803, 1999, 2026, 2482, 1005, 1055, 9573, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 11194, 2003, 2437, 2033, 2147, 1999, 17760, 3785, 2302, 2151, 9474, 6718, 2066, 11875, 2030, 15806, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 14939, 2003, 11193, 2000, 3477, 1996, 3222, 2000, 1996, 20138, 1998, 2085, 1996, 20138, 2003, 18820, 18965, 2033, 2005, 1996, 2769, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 2194, 2003, 11193, 1037, 25416, 8630, 2005, 1037, 1005, 13261, 1005, 3462, 2138, 1045, 17414, 2009, 2083, 1037, 2353, 1011, 2283, 9445, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 2194, 2003, 6932, 2149, 2000, 2147, 1999, 2019, 2436, 2007, 1005, 2053, 5372, 7497, 1005, 1998, 2256, 2159, 18743, 2003, 2893, 5360, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1045, 2572, 2893, 5377, 12403, 2213, 4455, 2013, 1037, 28516, 2008, 2758, 1045, 2031, 1037, 5592, 3403, 2005, 2033, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 11194, 2003, 2025, 7079, 1996, 1005, 17850, 2050, 1005, 6922, 1997, 2026, 10300, 2138, 1045, 2444, 1999, 2026, 2219, 2160, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 12508, 3478, 2000, 3073, 5763, 2373, 10200, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2026, 4316, 2001, 29116, 4417, 2004, 2304, 9863, 2098, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2619, 2003, 25044, 2075, 2033, 2478, 2214, 11834, 7696, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1045, 2179, 2026, 2434, 2470, 2951, 2006, 2250, 10796, 2108, 2109, 1999, 1037, 2231, 3189, 2302, 8951, 2026, 2817, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 11194, 2003, 2025, 12816, 2075, 1052, 2546, 7919, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1037, 2177, 3158, 9305, 3550, 2026, 4497, 2076, 2576, 8320, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1037, 7985, 14177, 2026, 8722, 1999, 3006, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1045, 2215, 2000, 2113, 2065, 1037, 2564, 2064, 4366, 1037, 3745, 1999, 1996, 2160, 2065, 2009, 1005, 1055, 1999, 1996, 4101, 2171, 1997, 2014, 3129, 1998, 2388, 1011, 1999, 1011, 2375, 102, 0, 0, 0, 0, 0, 0], [101, 1045, 2001, 16981, 2005, 2383, 1037, 1005, 7087, 3347, 1005, 2006, 2026, 15620, 2130, 2295, 2009, 2234, 2004, 1037, 3115, 25339, 2013, 1996, 2265, 9954, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2026, 3129, 2003, 2467, 9361, 2026, 2924, 11817, 1998, 4851, 2005, 28258, 2005, 2673, 1045, 4965, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1045, 2572, 2108, 2356, 2000, 3477, 4171, 2006, 1000, 8318, 2278, 5356, 29536, 22368, 1000, 6666, 2138, 1045, 2481, 1005, 1056, 3965, 1996, 1000, 2434, 3558, 8236, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1045, 2001, 16981, 2005, 1005, 2478, 1037, 4684, 3042, 1005, 2096, 1045, 2001, 2074, 2478, 1996, 2376, 1011, 3094, 3444, 1997, 2026, 2482, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1045, 2215, 1037, 8179, 2138, 2026, 3129, 2003, 2467, 21289, 2026, 2155, 1005, 1055, 2591, 3570, 1999, 2392, 1997, 2010, 2436, 2814, 1998, 5795, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2026, 4316, 2001, 18597, 1999, 5647, 2181, 2302, 5060, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 24641, 5645, 2003, 7386, 2075, 1996, 13582, 16927, 1012, 3183, 2323, 1045, 3967, 1029, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2026, 3129, 7906, 4129, 2033, 2008, 1045, 2572, 1005, 9743, 19068, 1005, 1998, 2008, 2003, 1996, 3114, 2339, 2002, 2003, 2025, 2893, 1037, 4712, 2012, 2147, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1045, 2215, 2000, 2113, 2065, 1045, 2064, 4366, 6032, 2065, 2026, 3129, 2003, 2019, 1005, 23850, 1005, 2266, 1997, 1037, 2155, 2449, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 3318, 4171, 9445, 2003, 21936, 2026, 2433, 2184, 2063, 2005, 10300, 12098, 16416, 2869, 2138, 1996, 11194, 1521, 1055, 9092, 2003, 2025, 3858, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 5005, 10796, 2013, 4713, 2003, 12473, 3518, 3901, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1037, 8275, 2924, 20587, 2356, 2005, 2026, 4003, 4751, 2000, 8116, 1037, 2047, 4003, 1998, 10312, 2026, 5703, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 4684, 3042, 2058, 20192, 3215, 1998, 3844, 2015, 2091, 2021, 2326, 2415, 2758, 2053, 3277, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 5005, 2013, 1996, 3518, 3919, 5470, 2003, 2437, 2009, 5263, 2005, 1996, 3901, 2000, 3637, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1037, 2334, 4825, 2003, 2478, 2026, 11749, 2098, 2171, 1005, 26389, 11253, 22254, 2401, 1005, 1998, 2130, 2026, 3563, 12183, 2640, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 3784, 2495, 4132, 2003, 2025, 4346, 2680, 4280, 2004, 5763, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1037, 2177, 1997, 2273, 2003, 10851, 1996, 2346, 2000, 1996, 2334, 2380, 1998, 13003, 1005, 4443, 9883, 1005, 2013, 1996, 2851, 22559, 2651, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 4684, 2326, 2415, 2921, 2026, 3042, 2005, 3134, 2302, 26296, 2009, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 6206, 23642, 1997, 1041, 1011, 5949, 2003, 6230, 2379, 5647, 2752, 1012, 2129, 2079, 1045, 5371, 1037, 12087, 1029, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 2334, 3447, 2003, 4352, 1037, 6081, 4713, 2000, 2448, 2503, 1037, 5123, 5780, 4224, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1045, 2572, 2108, 18476, 3550, 2005, 1000, 3308, 26236, 2078, 3642, 1000, 2006, 1037, 4031, 2008, 4212, 2104, 1996, 2324, 1003, 28177, 2102, 3446, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1045, 2215, 2000, 2113, 2065, 1045, 2064, 2131, 1996, 9968, 1997, 2026, 4268, 2065, 2026, 3129, 2003, 1037, 3082, 4677, 5610, 2099, 1998, 2019, 14813, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 28177, 2102, 9445, 2003, 2025, 10842, 1996, 1005, 2009, 2278, 1005, 2006, 1005, 12324, 1997, 2578, 1005, 2130, 2044, 1045, 3825, 1996, 4171, 2104, 22110, 2213, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1045, 3603, 2008, 2026, 3200, 2003, 2112, 1997, 2019, 1005, 5237, 1011, 2069, 4224, 1005, 1998, 2053, 2160, 2003, 3039, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 11194, 6439, 5567, 12087, 2055, 18917, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 2968, 2003, 2025, 4346, 1037, 1005, 13675, 27635, 1005, 2005, 1996, 5126, 1005, 2336, 2004, 2566, 1996, 2418, 7450, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1045, 2001, 6731, 2302, 7526, 2030, 5060, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2026, 2564, 2003, 8701, 2000, 6402, 2014, 2219, 2398, 1998, 2425, 1996, 2610, 2008, 2026, 2388, 2106, 2009, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 3208, 2003, 6932, 2033, 2000, 2224, 2026, 1005, 3167, 4923, 4003, 1005, 2005, 2035, 2194, 3604, 21725, 2015, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 19387, 2080, 2003, 9694, 1037, 1005, 2053, 2278, 1005, 2013, 1996, 4026, 2610, 2000, 3277, 1037, 2047, 21469, 2044, 1045, 2439, 2026, 2214, 2028, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2619, 10312, 5356, 2013, 2026, 2160, 2393, 2282, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2026, 3129, 2003, 13366, 10631, 3070, 2033, 1999, 9064, 4418, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2619, 2006, 9733, 2003, 4855, 1037, 3829, 11721, 24291, 2008, 2003, 2019, 6635, 6100, 1997, 2026, 16719, 15415, 14704, 2099, 2640, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1037, 23307, 2165, 2058, 2026, 7858, 3149, 1998, 2318, 2444, 11058, 6206, 4180, 2029, 2288, 2026, 3149, 6731, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 19387, 2080, 2003, 11193, 2000, 3277, 2026, 1005, 4439, 6105, 1005, 2138, 1996, 1005, 27178, 2361, 1005, 2005, 9779, 17516, 2906, 27280, 2003, 2025, 2746, 2651, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2026, 5795, 3084, 2033, 3524, 1999, 1996, 2436, 2005, 2093, 2847, 2044, 2026, 5670, 4515, 2074, 2000, 1005, 2192, 2058, 1996, 6309, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 19387, 2080, 2003, 11193, 2000, 4651, 2026, 2482, 2138, 2045, 2003, 1037, 1005, 5430, 4017, 1005, 2013, 2070, 2711, 1045, 2031, 2196, 2777, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1037, 4435, 1997, 1005, 3424, 1011, 22529, 1005, 13387, 2015, 2987, 1005, 1056, 2147, 2012, 2035, 1998, 2026, 2775, 2288, 2978, 2096, 4147, 2068, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2619, 2580, 1037, 8275, 5414, 10439, 2478, 2026, 2194, 8154, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 2482, 11033, 8394, 25416, 8630, 1997, 21725, 3815, 2044, 16990, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1037, 2334, 7390, 9338, 2003, 24731, 1996, 3563, 3919, 2640, 1997, 2026, 2400, 1011, 3045, 2436, 4624, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 12508, 2003, 11193, 2000, 3073, 1037, 1005, 13695, 6032, 8196, 1005, 2005, 1996, 2047, 2311, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2026, 7353, 4646, 2003, 5307, 2436, 17304, 1012, 2129, 2000, 6869, 1029, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 12508, 2003, 11193, 2000, 3073, 2019, 1005, 2053, 2278, 1005, 2013, 1996, 4483, 2604, 2005, 2256, 10200, 13103, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2026, 2564, 2003, 8701, 2000, 5371, 1037, 8275, 29603, 2553, 2114, 2026, 6422, 2567, 2040, 2003, 1037, 3026, 2231, 2961, 1999, 2178, 2110, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 6206, 23642, 1997, 2810, 11385, 1999, 5485, 1012, 2029, 3691, 16024, 2009, 1029, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 2924, 2003, 11193, 2000, 3073, 1037, 1005, 3558, 6100, 1005, 1997, 2026, 4923, 4003, 3820, 1998, 2003, 4851, 2005, 1037, 7408, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1037, 2177, 1997, 3337, 28186, 2308, 1999, 2256, 5701, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1037, 7985, 4457, 2026, 2567, 2076, 2782, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 19387, 2080, 2003, 11193, 2000, 20687, 2026, 1005, 6105, 1005, 2138, 1045, 2134, 1005, 1056, 10651, 2026, 1005, 16012, 12589, 2015, 1005, 2044, 4285, 2287, 2871, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2330, 19873, 9530, 15464, 28184, 2334, 8644, 2379, 2082, 1012, 3183, 2000, 12367, 1029, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1045, 2572, 2108, 2794, 2000, 3674, 19888, 2080, 1011, 9598, 2967, 2006, 2054, 3736, 9397, 2302, 2026, 6656, 1998, 2027, 2024, 12403, 25057, 2033, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1045, 2363, 1037, 8275, 2924, 9499, 2055, 1037, 2312, 10534, 1998, 2439, 2769, 2043, 1045, 2170, 1996, 2393, 4179, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1037, 5072, 3269, 7085, 1041, 4246, 7630, 11187, 2012, 2305, 1012, 2064, 1045, 5371, 1037, 12087, 1029, 102, 0, 0, 

In [40]:
val_encodings = tokenizer(
    val_texts,
    truncation=True,
    padding=True,
    max_length=128
)

In [41]:
test_encodings = tokenizer(
    test_texts,
    truncation=True,
    padding=True,
    max_length=128
)

In [42]:
import torch
from torch.utils.data import Dataset

class TextDataset(Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

In [43]:

val_dataset = TextDataset(val_encodings, val_labels)
test_dataset = TextDataset(test_encodings, test_labels)
train_dataset = TextDataset(train_encoding, train_labels)

In [44]:
len(train_dataset)

8142

In [45]:
from transformers import AutoModelForSequenceClassification

In [46]:
num_labels = len(label2id)
print(num_labels)

10

In [47]:
model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=num_labels,
    id2label=id2label,
    label2id=label2id
)

Loading weights: 100%|██████████| 100/100 [00:00<00:00, 878.56it/s, Materializing param=distilbert.transformer.layer.5.sa_layer_norm.weight]
DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
pre_classifier.bias     | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [48]:
model

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSelfAttention(
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=10, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)

In [49]:
from transformers import TrainingArguments, Trainer

In [50]:

from sklearn.metrics import accuracy_score,precision_recall_fscore_support
def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    
    preds = predictions.argmax(axis=1)
    
    precision, recall, f1, _ = precision_recall_fscore_support(
        labels, preds, average="weighted"
    )
    
    acc = accuracy_score(labels, preds)
    
    return {
        "accuracy": acc,
        "f1": f1,
        "precision": precision,
        "recall": recall
    }

In [52]:
training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_dir="./logs",
    load_best_model_at_end=True
)

`logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

In [53]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics
)

In [54]:
trainer.train()

C:\Users\Vishnu Manikandan\AppData\Roaming\Python\Python310\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.68it/s]
C:\Users\Vishnu Manikandan\AppData\Roaming\Python\Python310\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  6.01it/s]
C:\Users\Vishnu Manikandan\AppData\Roaming\Python\Python310\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.48it/s]
There were missing keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.weight', 'distilbert.embeddings.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.beta', 'distilbert.embeddings.LayerNorm.gamma'].

TrainOutput(global_step=1527, training_loss=0.14390976056602942, metrics={'train_runtime': 1035.3261, 'train_samples_per_second': 23.593, 'train_steps_per_second': 1.475, 'total_flos': 246500589652200.0, 'train_loss': 0.14390976056602942, 'epoch': 3.0})

In [55]:
trainer.evaluate()

C:\Users\Vishnu Manikandan\AppData\Roaming\Python\Python310\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

{'eval_loss': 0.09949683398008347,
 'eval_accuracy': 0.9816618911174785,
 'eval_f1': 0.9816690737764282,
 'eval_precision': 0.9817292847732975,
 'eval_recall': 0.9816618911174785,
 'eval_runtime': 15.9954,
 'eval_samples_per_second': 109.094,
 'eval_steps_per_second': 6.877,
 'epoch': 3.0}

In [115]:
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

predictions = trainer.predict(test_dataset)
preds = np.argmax(predictions.predictions, axis=1)

cm = confusion_matrix(test_labels, preds)
print("Confusion Matrix:\n", cm)

print("\nClassification Report:\n")
print(classification_report(test_labels, preds))

Confusion Matrix:
 [[72  0  0  0  0  0  0  1  0  0]
 [ 0 73  1  0  0  0  0  0  0  0]
 [ 2  1 69  0  0  0  0  0  0  0]
 [ 0  0  0 52  0  0  0  0  0  0]
 [ 0  0  0  0 79  0  0  0  0  0]
 [ 0  0  0  0  0 70  0  0  0  0]
 [ 0  0  0  0  0  0 34  0  0  0]
 [ 0  0  0  0  0  0  0 74  0  0]
 [ 0  1  0  0  0  0  0  0 71  0]
 [ 0  0  0  0  0  0  0  0  0 68]]

Classification Report:

              precision    recall  f1-score   support

           0       0.97      0.99      0.98        73
           1       0.97      0.99      0.98        74
           2       0.99      0.96      0.97        72
           3       1.00      1.00      1.00        52
           4       1.00      1.00      1.00        79
           5       1.00      1.00      1.00        70
           6       1.00      1.00      1.00        34
           7       0.99      1.00      0.99        74
           8       1.00      0.99      0.99        72
           9       1.00      1.00      1.00        68

    accuracy                           0.99       668
   macro avg       0.99      0.99      0.99       668
weighted avg       0.99      0.99      0.99       668

In [57]:
trainer.save_model("legal_classifier_model")
tokenizer.save_pretrained("legal_classifier_model")

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.84it/s]

('legal_classifier_model\\tokenizer_config.json',
 'legal_classifier_model\\tokenizer.json')